const config = {
    style: "mapbox://styles/dylanmaxwell/ckyhy6iu52xjg14ryq5onrzqu",
    accessToken: "pk.eyJ1IjoiZHlsYW5tYXh3ZWxsIiwiYSI6ImNrcTczNGtzNTAwcDYyb3BtdGN3em5ndGsifQ.df72_vr_4lG4QTdcwlXa-g",
    CSV: "https://docs.google.com/spreadsheets/d/1e_qbLSgl9XkOpbrzl9lFPJqyZZcnTyRm_WLcXpgxRho/gviz/tq?tqx=out:csv&sheet=Sheet1",
    center: [-96.164, 38.351],
    zoom: 3.5,
    title: "",
    description: "Filter Banner Stores by clicking the button below.",
    sideBarInfo: ["BANNER_NM"],
    popupInfo: ["BANNER_NM"],
    filters: [{
        type: "checkbox",
        title: "Albertsons Companies Banners: ",
        columnHeader: "BANNER_NM",
        listItems: [
            "SAFEWAY",
            "CARRS",
            "ALBERTSONS",
            "HAGGEN",
            "PAK N SAV BY SAFEWAY",
            "PAK N SAV",
            "VONS",
            "PAVILIONS",
            "MARKET STREET",
            "LUCKY",
            "ALBERTSONS MARKET",
            "UNITED",
            "AMIGOS",
            "RANDALLS",
            "TOM THUMB",
            "JEWEL-OSCO",
            "ACME",
            "SHAW'S",
            "STAR"
        ],
    }],
};